id: P009167
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30496
  title: གསེར་མདོག་ལས་སྦྲུམ་པའི་རོལ་དབྱངས།
  author: ''
  volumes:
    c3544f1aa2be439c9e76cc53443e3a41:
      image_group_id: I1KG12346
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
